---
- name: Init database
  ansible.builtin.shell: |
    {{ postgres_bin_dir }}/initdb "{{ postgres_data_dir }}"

- name: Enable listening
  ansible.builtin.blockinfile:
    path: "{{ postgres_data_dir }}/postgresql.conf"
    block: |
      listen_addresses = '*'
      port = 5432

- name: Enable connection
  ansible.builtin.blockinfile:
    path: "{{ postgres_data_dir }}/pg_hba.conf"
    block: |
      host all all {{ localhost_ip }} trust
      host all all {{ localnet_ip }} trust

- name: Start service
  ansible.builtin.shell: |
    {{ postgres_bin_dir }}/pg_ctl -D "{{ postgres_data_dir }}" -w -t 60 start
