---
- name: Import install install dependency
  ansible.builtin.import_tasks: ./install_install_dependency.yml
  tags: install_install_dependency

- name: Import install postgres
  ansible.builtin.import_tasks: ./install_postgres.yml
  tags: install_postgres
