services:
  {{ container_name }}:
    build: "{{ dst_docker_dir }}"
    image: "{{ image_name }}"
    container_name: "{{ container_name }}"
    restart: always
    ports:
      - "{{ ssh_port }}:22"
      - "{{ postgres_port }}:5432"
    expose:
      - "5432"
    volumes:
      - db_volume:/var/lib/postgresql
      - type: bind
        source: "{{ share_dir_on_baremetal }}"
        target: "{{ share_dir_on_container }}"
    networks:
      db_network:

volumes:
  db_volume:
    name: db_volume

networks:
  db_network:
    ipam:
      driver: default
      config:
        - subnet: "{{ dockernet_ip }}"
