---
- name: Make docker file directory
  ansible.builtin.file:
    path: "{{ dst_docker_dir }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"
    state: directory

- name: Copy public key
  ansible.builtin.copy:
    src: "{{ src_pubkey_file }}"
    dest: "{{ dst_pubkey_file }}"
    mode: "0600"

- name: Get uid
  ansible.builtin.gather_facts:

- name: Set uid
  ansible.builtin.set_fact:
    user_id: "{{ ansible_user_uid }}"

- name: Copy docker file
  ansible.builtin.template:
    src: "{{ src_docker_file }}"
    dest: "{{ dst_docker_file }}"
    mode: "0644"

- name: Build docker image
  community.docker.docker_image:
    build:
      path: "{{ dst_docker_dir }}"
    source: "build"
    name: "{{ image_name }}"
    state: "present"
