---
- name: Install pip packages
  ansible.builtin.pip:
    name:
      - requests==2.31.0
      - docker
      - docker-compose
  environment:
    http_proxy: "{{ proxy_setting }}"
    https_proxy: "{{ proxy_setting }}"
