---
- name: Create image table
  community.postgresql.postgresql_table:
    name: "{{ common_schema_name }}.{{ image_table_name }}"
    columns: "{{ image_items }}"
    login_host: "{{ db_host }}"
    port: "{{ db_port }}"
    login_db: "{{ db_name }}"
    login_user: "{{ manage_table_role_name }}"
  vars:
    query_string: "[*].join(' ', [name, type])"
    image_items: "{{ lookup('file', image_item_file) | from_json | json_query(query_string) }}"

- name: Grant to read image table
  community.postgresql.postgresql_privs:
    privs: SELECT
    schema: "{{ common_schema_name }}"
    objs: "{{ image_table_name }}"
    type: table
    roles: "{{ refer_role_name }}"
    grant_option: true
    login_host: "{{ db_host }}"
    port: "{{ db_port }}"
    login_user: "{{ manage_table_role_name }}"
    login_db: "{{ db_name }}"

- name: Insert init data into image table
  community.postgresql.postgresql_query:
    query: |
      INSERT INTO {{ common_schema_name }}.{{ image_table_name }}
      ( image_name, image_md5sum ) VALUES
      ( '{{ item.image_name }}', '{{ item.image_md5sum }}' )
    login_host: "{{ db_host }}"
    port: "{{ db_port }}"
    login_db: "{{ db_name }}"
    login_user: "{{ manage_table_role_name }}"
  loop: "{{ image_list }}"
  vars:
    image_list: "{{ lookup('file', image_list_file) | from_json }}"
