---
- name: Enable listening
  ansible.builtin.blockinfile:
    path: "{{ postgres_data_dir }}/postgresql.conf"
    block: |
      listen_addresses = '*'
      port = 5432

- name: Enable connection
  ansible.builtin.blockinfile:
    path: "{{ postgres_data_dir }}/pg_hba.conf"
    block: |
      host all all {{ localhost_ip }} trust
      host all all {{ dockernet_ip }} trust
      host all all {{ localnet_ip }} trust
