---
- name: Install apt packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - libpq-dev
  become: true

- name: Install pip packages
  ansible.builtin.pip:
    name:
      - psycopg2
  environment:
    http_proxy: ""
    https_proxy: ""
