---
- name: Check service status
  ansible.builtin.shell: |
    {{ postgres_bin_dir }}/pg_ctl -D "{{ postgres_data_dir }}" status
  register: status_result
  failed_when: status_result.rc not in [0, 3]

- name: Start service if it is not running
  ansible.builtin.shell: |
    {{ postgres_bin_dir }}/pg_ctl -D "{{ postgres_data_dir }}" -w -t 60 start
  when: status_result.rc == 3
  changed_when: true
