---
- name: Create administrator role
  community.postgresql.postgresql_user:
    name: "{{ admin_role_name }}"
    role_attr_flags: "LOGIN,CREATEDB,CREATEROLE"
    login_host: "{{ db_host }}"
    port: "{{ db_port }}"
    login_db: "postgres"

- name: Create manage schema role
  community.postgresql.postgresql_user:
    name: "{{ manage_schema_role_name }}"
    role_attr_flags: "LOGIN"
    login_host: "{{ db_host }}"
    port: "{{ db_port }}"
    login_user: "{{ admin_role_name }}"
    login_db: "postgres"

- name: Create manage table role
  community.postgresql.postgresql_user:
    name: "{{ manage_table_role_name }}"
    role_attr_flags: "LOGIN"
    login_host: "{{ db_host }}"
    port: "{{ db_port }}"
    login_user: "{{ admin_role_name }}"
    login_db: "postgres"

- name: Create refer role
  community.postgresql.postgresql_user:
    name: "{{ refer_role_name }}"
    role_attr_flags: "LOGIN"
    login_host: "{{ db_host }}"
    port: "{{ db_port }}"
    login_user: "{{ admin_role_name }}"
    login_db: "postgres"
