---
- name: Import install dependency
  ansible.builtin.import_tasks: ./install_dependency.yml
  tags: install_dependency

- name: Import init data
  ansible.builtin.import_tasks: ./init_data.yml
  tags: init_data

- name: Import create connection setting
  ansible.builtin.import_tasks: ./create_connection_setting.yml
  tags: create_connection_setting

- name: Import start database
  ansible.builtin.import_tasks: ./start_database.yml
  tags: start_database

- name: Import create database
  ansible.builtin.import_tasks: ./create_database.yml
  tags: create_database

- name: Import create role
  ansible.builtin.import_tasks: ./create_role.yml
  tags: create_role
